apiVersion: v1
kind: Secret
metadata:
  name: testing-fastapi-backend-secrets
  namespace: testing
type: Opaque
stringData:
  # Security
  SECRET_KEY: "orangsehat" # Ganti dengan random string yang panjang
  FIRST_SUPERUSER: "admin@example.com"
  FIRST_SUPERUSER_PASSWORD: "orangsehat"

  # Email Credentials
  SMTP_USER: ""
  SMTP_PASSWORD: ""

  # Database Credentials
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "admin123" # Password DB kamu

  # Other
  SENTRY_DSN: ""
